version: '2'
services:

  app:
    entrypoint: node /app/index.js
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis:3.2.11-alpine
    ports: 
      - 6380:6379
